import type { NewSkill } from '../src/schema/skills'

export const skillsData: NewSkill[] = [
  // Copywriting & Content (5)
  {
    name: 'copywriting',
    description:
      'Write marketing copy for pages - homepage, landing pages, pricing, features, about',
    type: 'with_rules',
    s3Key: 'skills/copywriting/',
    hasRules: true,
    hasSubdirectories: false,
    triggerKeywords: [
      'write copy',
      'rewrite',
      'marketing copy',
      'headline',
      'CTA',
      'homepage copy',
      'landing page copy',
      'pricing page',
      'feature page',
      'about page',
      'product page',
    ],
    relatedSkills: ['copy-editing', 'page-cro', 'email-sequence', 'popup-cro', 'ab-test-setup'],
  },
  {
    name: 'copy-editing',
    description: 'Edit, review, or improve existing marketing copy',
    type: 'simple',
    s3Key: 'skills/copy-editing/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'edit this copy',
      'review my copy',
      'copy feedback',
      'proofread',
      'polish this',
      'make this better',
      'copy sweep',
    ],
    relatedSkills: ['copywriting'],
  },
  {
    name: 'blog-strategy',
    description: 'Plan blog content strategy, create content briefs, or write blog posts',
    type: 'simple',
    s3Key: 'skills/blog-strategy/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'blog post',
      'content strategy',
      'editorial calendar',
      'SEO content',
      'thought leadership',
      'content brief',
      'article',
      'blog topics',
    ],
    relatedSkills: ['content-calendar', 'seo-audit'],
  },
  {
    name: 'video-script',
    description: 'Create video scripts for explainer videos, product demos, testimonials',
    type: 'simple',
    s3Key: 'skills/video-script/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'video script',
      'explainer video',
      'product demo',
      'demo video',
      'testimonial video',
      'social video',
      'video content',
      'YouTube script',
    ],
    relatedSkills: ['social-content'],
  },
  {
    name: 'social-content',
    description: 'Create, schedule, or optimize social media content',
    type: 'simple',
    s3Key: 'skills/social-content/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'LinkedIn post',
      'Twitter thread',
      'social media',
      'content calendar',
      'social scheduling',
      'engagement',
      'viral content',
      'TikTok',
      'Instagram',
    ],
    relatedSkills: ['content-calendar', 'launch-strategy'],
  },

  // CRO & Optimization (7)
  {
    name: 'page-cro',
    description: 'Optimize, improve, or increase conversions on any marketing page',
    type: 'with_rules',
    s3Key: 'skills/page-cro/',
    hasRules: true,
    hasSubdirectories: false,
    triggerKeywords: [
      'CRO',
      'conversion rate optimization',
      "this page isn't converting",
      'improve conversions',
      "why isn't this page working",
      'optimize page',
    ],
    relatedSkills: ['signup-flow-cro', 'onboarding-cro', 'form-cro', 'popup-cro'],
  },
  {
    name: 'signup-flow-cro',
    description: 'Optimize signup, registration, account creation flows',
    type: 'simple',
    s3Key: 'skills/signup-flow-cro/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'signup conversions',
      'registration friction',
      'signup form optimization',
      'free trial signup',
      'reduce signup dropoff',
      'account creation flow',
    ],
    relatedSkills: ['onboarding-cro', 'form-cro'],
  },
  {
    name: 'onboarding-cro',
    description: 'Optimize post-signup onboarding, user activation, first-run experience',
    type: 'simple',
    s3Key: 'skills/onboarding-cro/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'onboarding flow',
      'activation rate',
      'user activation',
      'first-run experience',
      'empty states',
      'onboarding checklist',
      'aha moment',
      'new user experience',
    ],
    relatedSkills: ['signup-flow-cro', 'email-sequence'],
  },
  {
    name: 'form-cro',
    description:
      'Optimize forms that are NOT signup/registration - lead capture, contact, demo request',
    type: 'simple',
    s3Key: 'skills/form-cro/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'form optimization',
      'lead form conversions',
      'form friction',
      'form fields',
      'form completion rate',
      'contact form',
    ],
    relatedSkills: ['signup-flow-cro', 'page-cro'],
  },
  {
    name: 'popup-cro',
    description: 'Create or optimize popups, modals, overlays, slide-ins, banners',
    type: 'simple',
    s3Key: 'skills/popup-cro/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'exit intent',
      'popup conversions',
      'modal optimization',
      'lead capture popup',
      'email popup',
      'announcement banner',
      'overlay',
    ],
    relatedSkills: ['form-cro', 'page-cro'],
  },
  {
    name: 'paywall-upgrade-cro',
    description: 'Create or optimize in-app paywalls, upgrade screens, upsell modals',
    type: 'simple',
    s3Key: 'skills/paywall-upgrade-cro/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'paywall',
      'upgrade screen',
      'upgrade modal',
      'upsell',
      'feature gate',
      'convert free to paid',
      'freemium conversion',
      'trial expiration screen',
      'limit reached screen',
      'plan upgrade prompt',
      'in-app pricing',
    ],
    relatedSkills: ['pricing-strategy', 'onboarding-cro'],
  },
  {
    name: 'ab-test-setup',
    description: 'Plan, design, or implement A/B tests and experiments',
    type: 'simple',
    s3Key: 'skills/ab-test-setup/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'A/B test',
      'split test',
      'experiment',
      'hypothesis',
      'test this change',
      'variant copy',
      'multivariate test',
    ],
    relatedSkills: ['analytics-tracking', 'page-cro'],
  },

  // Email & Sequences (2)
  {
    name: 'email-sequence',
    description: 'Create email sequences - welcome, nurture, onboarding, re-engagement campaigns',
    type: 'with_rules',
    s3Key: 'skills/email-sequence/',
    hasRules: true,
    hasSubdirectories: false,
    triggerKeywords: [
      'email sequence',
      'drip campaign',
      'nurture sequence',
      'onboarding emails',
      'welcome sequence',
      're-engagement emails',
      'email automation',
      'lifecycle emails',
    ],
    relatedSkills: ['copywriting', 'onboarding-cro'],
  },
  {
    name: 'content-calendar',
    description: 'Plan, schedule, or coordinate content across channels',
    type: 'simple',
    s3Key: 'skills/content-calendar/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'content calendar',
      'editorial calendar',
      'content planning',
      'batch content',
      'campaign planning',
      'content schedule',
      'publishing schedule',
      'content coordination',
      'content batching',
    ],
    relatedSkills: ['email-sequence', 'social-content', 'blog-strategy'],
  },

  // SEO & Technical (4)
  {
    name: 'seo-audit',
    description: 'Audit, review, or diagnose SEO issues on a site',
    type: 'simple',
    s3Key: 'skills/seo-audit/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'SEO audit',
      'technical SEO',
      'why am I not ranking',
      'SEO issues',
      'on-page SEO',
      'meta tags review',
      'SEO health check',
    ],
    relatedSkills: ['programmatic-seo', 'schema-markup'],
  },
  {
    name: 'schema-markup',
    description: 'Add, fix, or optimize schema markup and structured data',
    type: 'simple',
    s3Key: 'skills/schema-markup/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'schema markup',
      'structured data',
      'JSON-LD',
      'rich snippets',
      'schema.org',
      'FAQ schema',
      'product schema',
      'review schema',
      'breadcrumb schema',
    ],
    relatedSkills: ['seo-audit'],
  },
  {
    name: 'programmatic-seo',
    description: 'Create SEO-driven pages at scale using templates and data',
    type: 'simple',
    s3Key: 'skills/programmatic-seo/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'programmatic SEO',
      'template pages',
      'pages at scale',
      'directory pages',
      'location pages',
      '[keyword] + [city] pages',
      'comparison pages',
      'integration pages',
      'building many pages for SEO',
    ],
    relatedSkills: ['seo-audit', 'competitor-alternatives'],
  },
  {
    name: 'analytics-tracking',
    description: 'Set up, improve, or audit analytics tracking and measurement',
    type: 'simple',
    s3Key: 'skills/analytics-tracking/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'set up tracking',
      'GA4',
      'Google Analytics',
      'conversion tracking',
      'event tracking',
      'UTM parameters',
      'tag manager',
      'GTM',
      'analytics implementation',
      'tracking plan',
    ],
    relatedSkills: ['ab-test-setup'],
  },

  // Strategy & Positioning (5)
  {
    name: 'positioning',
    description: 'Create brand positioning, messaging frameworks, value propositions',
    type: 'simple',
    s3Key: 'skills/positioning/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'positioning statement',
      'value proposition',
      'messaging framework',
      'brand messaging',
      'positioning strategy',
      'category design',
      'market positioning',
      'competitive positioning',
    ],
    relatedSkills: ['customer-research', 'competitor-research'],
  },
  {
    name: 'pricing-strategy',
    description: 'Help with pricing decisions, packaging, monetization strategy',
    type: 'simple',
    s3Key: 'skills/pricing-strategy/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'pricing',
      'pricing tiers',
      'freemium',
      'free trial',
      'packaging',
      'price increase',
      'value metric',
      'Van Westendorp',
      'willingness to pay',
      'monetization',
    ],
    relatedSkills: ['paywall-upgrade-cro'],
  },
  {
    name: 'launch-strategy',
    description: 'Plan a product launch, feature announcement, or release strategy',
    type: 'simple',
    s3Key: 'skills/launch-strategy/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'launch',
      'Product Hunt',
      'feature release',
      'announcement',
      'go-to-market',
      'beta launch',
      'early access',
      'waitlist',
      'product update',
    ],
    relatedSkills: ['press-release', 'social-content'],
  },
  {
    name: 'free-tool-strategy',
    description: 'Plan and build a free tool for marketing purposes - lead generation, SEO',
    type: 'simple',
    s3Key: 'skills/free-tool-strategy/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'engineering as marketing',
      'free tool',
      'marketing tool',
      'calculator',
      'generator',
      'interactive tool',
      'lead gen tool',
      'build a tool for leads',
      'free resource',
    ],
    relatedSkills: ['programmatic-seo'],
  },
  {
    name: 'marketing-ideas',
    description: 'Marketing ideas, inspiration, or strategies for SaaS products',
    type: 'simple',
    s3Key: 'skills/marketing-ideas/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'marketing ideas',
      'growth ideas',
      'how to market',
      'marketing strategies',
      'marketing tactics',
      'ways to promote',
      'ideas to grow',
    ],
    relatedSkills: [],
  },

  // Research & Analysis (5)
  {
    name: 'competitor-research',
    description: 'Research, analyze, or monitor competitors',
    type: 'simple',
    s3Key: 'skills/competitor-research/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'competitive analysis',
      'competitor intel',
      'market positioning',
      'battlecard',
      'win/loss analysis',
      'competitive landscape',
      'competitor tracking',
      'market research',
      'competitive intelligence',
    ],
    relatedSkills: ['competitor-alternatives', 'positioning'],
  },
  {
    name: 'competitor-alternatives',
    description: 'Create competitor comparison or alternative pages for SEO and sales',
    type: 'simple',
    s3Key: 'skills/competitor-alternatives/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'alternative page',
      'vs page',
      'competitor comparison',
      'comparison page',
      '[Product] vs [Product]',
      '[Product] alternative',
      'competitive landing pages',
    ],
    relatedSkills: ['competitor-research', 'programmatic-seo'],
  },
  {
    name: 'customer-research',
    description: 'Conduct customer research, create interview scripts, design surveys',
    type: 'simple',
    s3Key: 'skills/customer-research/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'customer interview',
      'user research',
      'survey design',
      'buyer persona',
      'ICP',
      'ideal customer profile',
      'voice of customer',
      'VOC',
      'jobs to be done',
      'JTBD',
      'customer insights',
    ],
    relatedSkills: ['positioning'],
  },
  {
    name: 'marketing-psychology',
    description: 'Apply psychological principles and mental models to marketing',
    type: 'simple',
    s3Key: 'skills/marketing-psychology/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'psychology',
      'mental models',
      'cognitive bias',
      'persuasion',
      'behavioral science',
      'why people buy',
      'decision-making',
      'consumer behavior',
    ],
    relatedSkills: ['copywriting', 'page-cro'],
  },
  {
    name: 'idea-to-spec',
    description:
      'Expert consultant for brainstorming and turning ideas into specs, SOPs, plans, PRDs',
    type: 'complex',
    s3Key: 'skills/idea-to-spec/',
    hasRules: false,
    hasSubdirectories: true,
    triggerKeywords: [
      'brainstorm',
      'spec this out',
      'help me think through',
      'I have an idea',
      'plan this',
      'flesh out',
      'what would it take',
      'turn this into a plan',
      'SOP',
      'standard operating procedure',
      'PRD',
      'requirements doc',
      'decision doc',
      'business case',
    ],
    relatedSkills: [],
  },

  // Sales & Growth (6)
  {
    name: 'sales-enablement',
    description: 'Create sales collateral - one-pagers, battlecards, cold emails, sales decks',
    type: 'simple',
    s3Key: 'skills/sales-enablement/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'sales collateral',
      'one-pager',
      'battlecard',
      'cold email',
      'sales deck',
      'outbound email',
      'objection handling',
      'sales script',
      'product one-pager',
    ],
    relatedSkills: ['case-study', 'competitor-research'],
  },
  {
    name: 'case-study',
    description: 'Create customer success stories, case studies, testimonials',
    type: 'simple',
    s3Key: 'skills/case-study/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'case study',
      'customer story',
      'success story',
      'testimonial',
      'social proof',
      'customer win',
      'reference customer',
    ],
    relatedSkills: ['sales-enablement'],
  },
  {
    name: 'press-release',
    description: 'Create press releases, media pitches, PR communications',
    type: 'simple',
    s3Key: 'skills/press-release/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'press release',
      'media pitch',
      'PR announcement',
      'funding announcement',
      'launch press release',
      'media outreach',
      'journalist pitch',
      'founder story',
    ],
    relatedSkills: ['launch-strategy'],
  },
  {
    name: 'referral-program',
    description: 'Create, optimize, or analyze a referral program, affiliate program',
    type: 'simple',
    s3Key: 'skills/referral-program/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'referral',
      'affiliate',
      'ambassador',
      'word of mouth',
      'viral loop',
      'refer a friend',
      'partner program',
    ],
    relatedSkills: ['partnership-marketing'],
  },
  {
    name: 'partnership-marketing',
    description: 'Plan and execute partnership marketing, co-marketing initiatives',
    type: 'simple',
    s3Key: 'skills/partnership-marketing/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'partnership',
      'co-marketing',
      'joint webinar',
      'partner program',
      'integration partners',
    ],
    relatedSkills: ['referral-program'],
  },
  {
    name: 'retention-strategy',
    description: 'Improve retention, prevent churn, create win-back campaigns',
    type: 'simple',
    s3Key: 'skills/retention-strategy/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'retention',
      'churn',
      'churn prevention',
      'win-back',
      'customer health',
      'expansion revenue',
      'upsell',
      'NPS',
      'customer success',
      'reactivation',
    ],
    relatedSkills: ['email-sequence', 'onboarding-cro'],
  },

  // Advertising (1)
  {
    name: 'paid-ads',
    description: 'Help with paid advertising campaigns on Google, Meta, LinkedIn, Twitter/X',
    type: 'simple',
    s3Key: 'skills/paid-ads/',
    hasRules: false,
    hasSubdirectories: false,
    triggerKeywords: [
      'PPC',
      'paid media',
      'ad copy',
      'ad creative',
      'ROAS',
      'CPA',
      'ad campaign',
      'retargeting',
      'audience targeting',
    ],
    relatedSkills: ['analytics-tracking'],
  },
]
